### ISSUE TITLE
Create common createtab() function 

### ISSUE THREAD

**Issue by flamingice** [SuperNETorg/iguana_dev#1]
if you look at index.html, you will see that the same code is repeated for each tab

this is not good as you need to make the same fix in all places if ever you need to change the tab code

plus it is just hard to see the other code when there is so much

it is like having the same paragraph cut and pasted N times, with just 2 words different in each paragraph
​

a JS function can be created to just spit out the existing "paragraph" as a template, substituting just the words that are changed

**Comment by black-owling** [comment]
We can use existing JS template engine ( like http://handlebarsjs.com/ ) instead of creating our own.

**Comment by ablaze8** [comment]
I am wondering how open are we to use AngularJS ?

**Comment by black-owling** [comment]
I thought of it too.

**Comment by flamingice** [comment]
That is totally undecided, whatever fits best should be used.

**Comment by ablaze8** [comment]
IMO, AngualrJS is by far the most popular as far as I know. If the team agrees, I can prepare prototype. What do you think @black-owling, @flamingice, @mezzovide , @jl777  & @SuperNETorg/iguana-html-team  ? Please let us know if you have any questions / suggestions or concerns.

**Comment by black-owling** [comment]
I think it would be good fit. One minus is that I have only basic understanding of it.

**Comment by flamingice** [comment]
I will post some links I find as I try to find out what would be best to use.
* https://medium.com/@mnemon1ck/why-you-should-not-use-angularjs-1df5ddf6fc99#.58lw4z1hi
* https://medium.com/este-js-framework/what-i-would-recommend-instead-of-angular-js-62b057d8a9e#.j2xbc9e27

**Comment by black-owling** [comment]
I often see articles like those, but still it's very popular and there are a lot of devs using it. Well, since we need only to build UI - we can listen to author at second link - "For view aka user interface, use React.js.".

**Comment by ablaze8** [comment]
@black-owling : I am sure there are tons of resources out there. I am sure you are in good hands.
@flamingice : I am sure world has opinions on both the ends, we need to use what best fits us.

I have self taught myself AngularJS and KnockoutJs ... and frankly may folks I know ended up switching to AngularJs sooner or later - just my observation. The reason, I personally think we should use AngualrJS is [because of these reasons.] (http://www.sitepoint.com/10-reasons-use-angularjs/)

[Quick search on Google Trends] (http://bit.ly/1lQu6oL)

[Neutral comparison] (http://www.datahaunting.com/jquery/angularjs-vs-knockout-js-vs-backbone-js-vs-ember-js/)

**Comment by black-owling** [comment]
I prefer to get Angular experience.

**Comment by flamingice** [comment]
http://ilikekillnerds.com/2015/01/aurelia-vs-angularjs-round-one-fight/ - http://aurelia.io/ looks really interesting imo.

**Comment by Tosch110** [comment]
I have also spend some time mapping out a framework for instantdex, which is now part of iguana aswell. I have chosen React, because it has an awesome performance for larger apps and really nice workflow.
I would like to emphasize that with React you build Components which embody a certain functionality. So theoretically you are building a lot of little small applications which then eventually form the complete App. React makes sure that for every interaction you do, just the Components that care about an update gets rendered in the DOM.

This picture shows how you can imagine a website with the React Component structure:
http://maketea.co.uk/images/2014-03-05-robust-web-apps-with-react-part-1/wireframe_deconstructed.png

So a very good extra React brings us is that we can build a React Component for every tool iguana should have. Like the Blockexplorer, Pangea, InstantDex. People can be working within their component without being afraid of breaking something outside of the component. Also the React Component could easily be used to make a copy and deploy a new App out of the InstantDEX component. 

If you have not seen React before, check it out:
https://facebook.github.io/react/docs/getting-started.html

With React there are tools at hand like React Router which makes it easy to create a pagination. But React does not come with any template. So another thing to debate would be sticking to bootstrap. A lot of attention has turned to google Material UI which is made especially for React:

You can see that here:
http://www.material-ui.com/#/

This is all open to discussion which is very important at the beginning and I am very happy seeing so many people participate here!
The last tool I wanted to show helped made me choose react is this amazing charting library, which can help to make a good user experience for Data from the Blockchain or Exchanges:

https://github.com/rrag/react-stockcharts

Thanks! 
Tosch

**Comment by ablaze8** [comment]
@flamingice : Aurelia is spawned from AngularJS by one of it's core developers - due to some religious difference of opinions / politics. I personally did not have the chance to spend more than few hours.

**Comment by black-owling** [comment]
I think this should be here:

pnacl pexe is emscriptem javascript bytecodes running in a chrome os sandbox
​[5:09] 
there are some JS things that violate the sandbox restrictions
​[5:10] 
so there are html that is compatible with chrome browser that is rejected by pnacl sandbox, ie webix

**Comment by flamingice** [comment]
We will use REACT but as far as I understood that is more of a beautifulgui thing and not necessary for the uglygui we're working on in this repo. 

Lets get back to the initial topic - the "Create common createtab() function". Who can do it?

**Comment by fimkrypto** [comment]
Hi,

@noashh on the supernet forum asked me to weigh in, I was away most of this week hence the late reaction.

Before choosing React and some other MVC solution over Angular you should think about this:

***1***

If you don't like 'opinionated' development tools like Angular you should ask yourselves what better opinion do any of you have than the 'opinion' of the majority of the developers of one of the biggest and most successful Javascript frameworks out there.

The reason you need an opinionated framework is to avoid any individual developer doing it 'his way' probably just because he/she thinks it looks better that way (or some other subjective reason).

There are many books written on doing Angular the proper way, it is highly doubtful all of you have read all of them which leaves a lot of room for improving all your individual skills. Which is exactly what will happen when you work with a tool (it's called learning). After a while you'll likely come to the conclusion that big parts of the code are of bad quality now that you have better insight. Having books which express opinions on how to code a piece of software is an invaluable tool to be able to form the best consensus on where to take it from there.

***2***

A remark was made that this app that you are building is *just* UI which is why you did not require the full stack of services that angular offers. This is just plain wrong. The most complex parts you will run into have not emerged yet. Have you solved translation? http connection pooling? perhaps websocket subscribe/release management? endless scrolling, virtual lazy loading list buffers? For all this stuff the Angular community offers great 'opinionated' solutions.

***3***

As for the Component based paradigm that React is all about. This is available in Angular too and is indeed a very good way to build up your app.

Anyway good luck making a choice on framework.
Dirk

**Comment by flamingice** [comment]
Thank you for the input Dirk.

Copy/pasting this here from # iguana slack room. He worked with React.
"Tosch says basically everything necessary for instantdex is already there. The iguana_html zip is supposed to have the framework inside. In the old version (the one in the iguana_dev repo now) there is a draft for communication with api.js. he old "framework" (what we have in iguana_dev now) is a proof-of-concept for embeding pnacl. Tosch was not able to embed the pnacl into the new framework, it didnt work for him. The new framework is one with pagination, bootstrap and all node tools necessary to realize instantdex. The old api concept has to be transferred to the new, in React it uses "Stores" for a structured flow of information. That structured flow makes it easy to have different components and developers.

It is important to discuss with james how a user authenticates himself (so far discussed theoretically). Then one can start to get the information from exchanges, which allows populating the tables with data.

Breakdown:

    User authentication

    Get data we want to display

    Establish API communication for buy + sell (order doesnt matter. Polo, Bter, NXT AE, ...)

    Create GUI with charts etc.

    Polish

The "old" framework is really basic. It doesnt use much more than jquery and a selfmade pagination. It is proof-of-concept. Should not but could be used as base where react could be embeded easily."

https://sprnt.slack.com/files/noashh/F0GH52PT2/iguana_html.zip


https://sprnt.slack.com/files/noashh/F0GH52PT2/iguana_html.zip

**Comment by ablaze8** [comment]
@flamingice:

Let's hash few things up, I want to make sure that we see the real picture as well as rosy picture of ReactJS.

Questions

1. ReactJS is just a presentation layer, it does not do what AngualrJS do - like two way databinding, correct ? I do not see clean code without it ! Well there is "synthetic sugar way" of doing it but it is in the DNA of Angular with $scope to do it for you ! ( Source : http://facebook.github.io/react/docs/two-way-binding-helpers.html )
2. ReactJS is still young, and might make us re-invent the wheels ! ( Source: http://blog.andrewray.me/reactjs-for-stupid-people/ ) Where as Google's Angular has been around for a while now, with its initial release in 2009
3. Is the community as active as AngularJs ?
4. React requires that you build a class to define what HTML to render any way, in AgularJS, we do not "have to" !

Angular is a much fuller featured framework than React, which isn’t really a framework at all.

**Comment by flamingice** [comment]
@Tosch110 could you please add your opinion here

Interesting read: http://wildermuth.com/2015/9/1/Angular_v_React_v_Aurelia_v_et_al

I.e.: 
"I also am adopting Aurelia. I have used angular 1.x in the past and was largely happy with it, but I was very put off by the way 2 was handled and a lot of the news and examples I have seen. Angular 2 is likely much better than I fear and it certainly has a lot of market share. However, I have loved using Aurelia. It doesn't really feel like I'm using a framework so much as just using ES6/7. The design decisions seem to strive for simplification and getting out of the way rather creating new, foreign seeming concepts and syntax. I think I am picking Aurelia for now because it seems like it will be easier to use and I trust the future of a framework more when it seems to strive for elegance in simplicity."

One goal is to finish InstantDEX asap. Tosch tells me that the framework decision he made allows us to have a working InstantDEX already - it just needs dev work. So I see a part of the way has already been passed. I don't know if switching to AngularJS will make us deliver working iguana + instantdex faster than continuing what Tosch began. 

Seeing that @ablaze8 works alot it might make sense to use the framework he knows very well.

**Comment by ablaze8** [comment]
I want the team to agree, do not want to impose anything. If I had more experience with ReactJS would you use that rather ? ;-) If you really are looking for my opinion, I think considering the size and complexity we should use plain JavaScript only.

**Comment by flamingice** [comment]
Is JavaScript enough for uglygui?

Is it possible to have instantdex in React and have that as 1 tab in the uglyguy (while uglygui beeing just JavaScript)?

**Comment by ablaze8** [comment]
What is "uglygui" ?

**Comment by flamingice** [comment]
functionality based GUI

**Comment by ablaze8** [comment]
You meant something like the UI prototype ? Just to test the API ...

**Comment by flamingice** [comment]
Yes. Usable but without any chances to win design contests.

iguana_dev - functionality based GUI in debug mode. It is to expose and demonstrate how to use the iguana API.
iguana_stable - look and feel based GUI with packaged chrome app, and test plans - half of that repo is about the marketing text, graphics, branding, etc

**Comment by ablaze8** [comment]
Well, we can always experiment in dev and continue working with uglyui. The reason I suggested JavaScript, HTML5 and CSS3 was we don't have browser compatibly to worry about. And I am guessing that the total size of current html and js code would be lesser than any of  such libraries. We can still have some options of using Bootstrap's themes rather getting stuck with the default template. Anyway I don't want to sound too hard-core.


As I've said before, I'm not advocating anything over the other. But want to find out what that the dev team is most confident and what are their opinions ? If they're using something they already know and is proven, we can ramp up much faster from delivery perspective.

Plus my personal opinion is AngularJS would in a way force you to have clean code. ( just my opinion )

Again, I'd say to the team that try to keep JavaScript code as much decoupled from framework as possible, and try to follow some standard patterns so that a new teammate can understand the code structure easily.

I'm okay with whatever we end up using ... as long as we know pros  & cons  I'd leave it upto the team.

**Comment by flamingice** [comment]
For now lets use JavaScript, HTML5 and CSS3 in this repository. If we need more we can discuss it once the time has come. Do you agree?

**Comment by ablaze8** [comment]
Yes. And do you answer questions? Yes, we can use AngularJS and ReactJS together.

**Comment by vineetbhargav86** [comment]
Just to let everyone know, I am taking it up. @flamingice Can you please assign it to me if anyone else is not working on this

**Comment by flamingice** [comment]
@vineetbhargav86 I added you to the team, I think you can now self-assign the task.

**Comment by ablaze8** [comment]
@vineetbhargav86, no forking please. Please refer :

https://slack-files.com/T02LAJBUW-F0GS43ZCH-cd5662701f

https://slack-files.com/T02LAJBUW-F0GT14PM2-311152d6ea

**Comment by vineetbhargav86** [comment]
@flamingice Thanks for adding me to team but i still can not assign this issue to myself.

@ablaze8 Thanks for the migration guide. I will create a new branch and will point my local repository to main repository.

**Comment by flamingice** [comment]
@vineetbhargav86 you have to accept the invitation :-) http://i.imgur.com/Iu1uty0.png

**Comment by vineetbhargav86** [comment]
@flamingice  Sorry, my bad! I have accepted the invite and assigned this issue to myself.Thanks for your help.

**Comment by vineetbhargav86** [comment]
@flamingice I have been working on creating a function that will create html based on a json. This will help us remove lot of duplicate code and standardize/streamline the look and feel of UI elements.

Let's have a look how it looks. Consider the following JSON - 

{
	"panel" : {
		"panelHeading": {
			"attr"	: {"id" : "tab-heading", "class" : "tab-heading-class"},
			"value" : "Tab heading generated from template"
		},
		"panelBody": {
			"tablist" : [
				{
					"label" : "First Tab Label",
					"content" : {
						"table" : {
							"tableHeaders" : ["Symbol1", "Description", "Status", "Action"],
							"tableBody" : ""
						}
					}
				},
				{
					"label" : "Second Tab Label",
					"content" : {
						"table" : {
							"tableHeaders" : ["Symbol2", "Description", "Status", "Action"],
							"tableBody" : ""
						}
					}
				}
			]
		}
	}
}

This json will be converted into a tab/page with following html code - 

<div class="panel panel-default">
  <div class="panel-heading" id="tab-heading">
     <h3><span>Tab heading generated from template</span></h3>
  </div>
  <div class="panel-body">
     <ul class="nav nav-pills" role="tablist">
        <li role="presentation" class="active"><a href="#{{processedLabel}}" aria-controls="home" role="tab" data-toggle="tab">First Tab Label</a></li>
        <li role="presentation" class="active"><a href="#{{processedLabel}}" aria-controls="home" role="tab" data-toggle="tab">Second Tab Label</a></li>
     </ul>
     <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="{{processedLabel}}">
           <table id="Coins_table" class="table table-hover table-bordered">
              <thead>
                 <tr>
                    <th>Symbol1</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Action</th>
                 </tr>
              </thead>
              <tbody></tbody>
           </table>
        </div>
        <div role="tabpanel" class="tab-pane active" id="{{processedLabel}}">
           <table id="Coins_table" class="table table-hover table-bordered">
              <thead>
                 <tr>
                    <th>Symbol2</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Action</th>
                 </tr>
              </thead>
              <tbody></tbody>
           </table>
        </div>
     </div>
  </div>
</div>

I am just giving it finishing touch. Let me know what you think about it. All the code is committed in common_tab_creation branch

**Comment by flamingice** [comment]
I am not a coder so cant judge myself, when other devs find it helpful aswell then it is probably fine. (I copy+pasted the initial task description from someone, maybe james, cant remember.)

**Comment by msg4vivek** [comment]
Point from the discussion today, - this task is not being worked upon for now. 
ablaze: @flamingice seem to create this task.I'm trying to help my self understand. Each tab is not same, one is for block explorer,  one for coin, peers, settings ... They all do different things.Would someone please tell me why the task reads "same paragraphs" ... What does it mean ?
​11:41 : Until and unless we want to use html templets or AngularJS  directives ... this doesn't make sense to me.
stacksavings : flamingice commented 10 days ago. For now lets use JavaScript, HTML5 and CSS3 in this repository. If we need more we can discuss it once the time has come. Do you agree? that is what we went off of, using plain JS 

ablaze : No objections, and this task doesn't seem to be making any sense to me for the time being.I think our primary goal should be testing API and adding functions and working on GUI.This should come after we've figured other more important stuff and code base doesn't change this rapid.
In principle just before moving to pretty UI from ugly UI, this should be a part of code clean up exercise. Which would also consist of cleaning up and consolidating API calls etc. As we can't foresee lets not worry about common tab function. As all tabs are doing different things, and we don't want to complicate things unnecessarily.(edited)

stacksavings: ok yea I agree.. we have worked on implementing this based on the info we had at the time, it should work the same as current tab but just generate the HTML from JSON..
​
I agree there are bigger things to tackle and we would like to move on to something else, shoud we merge in what we have worked on so far?

ablaze : Let's not spend time on that please - my opinion.

stacksavings : so I want to get this closed out
​
ablaze: I know there was a discussion about frameworks and I was able to convince that we either use the best f/w ( AngularJS ) or none ( plain JavaScript ). I'm afraid I didn't assign that task to anyone as urgent and important issue.(edited)

stacksavings: I am fine with leaving this for now

**Comment by stacksavings** [comment]
@msg4vivek we did work on it though and made a commit

**Comment by flamingice** [comment]
moved to https://phabricator.supernet.org/T357
