### ISSUE TITLE
Develop iguana app store for agents 

### ISSUE THREAD

**Issue by flamingice** [SuperNETorg/iguana_dev#10]
http://wiki.supernet.org/wiki/Agents (Might be partially outdated. Agents are like extensions or modules. Sometimes you want ie. raw iguana + pangea poker based on it, making that iguana setup just a poker game app, without fancy trading, charts, bitcoin-blockchain-hosting etc.)

User wants to extend functionality of iguana, ie. play decentralized poker "Pangea". He opens the "App Store" and either searches for "Poker" or clicks on "Games -> Card Games -> Poker". He sees small boxes with a rating (like imdb), screenshot/logo, title. He can chose between different ways of displaying the info, how detailed, if list view, tiles, .... He can install the agent he likes, read changelog, give feedback himself. We can get more ideas from all the different app-store-like systems, ie. Google Play, Apple Appstore, Netflix, IMDB.

**Comment by jl777** [comment]
I have in mind a way to allow the old style agents to interoperate with chrome agents. So it is possible there is nothing to do here. The new chrome agents will use a different method due to the nature of pexe instances. Instead of being launched by a main process, each chrome agent will need to register with the main process. I will add this to the basic iguana a bit later and once that is done, it can be used as a template for all other chrome agents

**Comment by flamingice** [comment]
Task in phab https://phabricator.supernet.org/T275
